name: build distributions
run-name: ${{ github.actor }} is building
on:
  push:
    branches:
      - main
      - develop
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: download jmods
        run: wget https://download2.gluonhq.com/openjfx/19/openjfx-19_linux-x64_bin-jmods.zip -O javafx-jmods-19.zip
      - name: unpack jmods
        run: unzip javafx-jmods-19.zip
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug -p javafx-jmods-19 --add-modules javafx.controls,javafx.fxml,javafx.base,javafx.graphics --output target/JRE
      - name: jpackage
        run: jpackage --type deb --input target/ --main-jar holocron-0.1-SNAPSHOT.jar --main-class MainApplication --runtime-image target/JRE/ --linux-shortcut --name holocron
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: holocron_*_amd64.deb
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: download jmods
        run: curl -L -o javafx-jmods-19.zip -0 https://download2.gluonhq.com/openjfx/19/openjfx-19_windows-x86_bin-jmods.zip
      - name: unpack jmods
        run: tar -xf javafx-jmods-19.zip
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug -p javafx-jmods-19 --add-modules javafx.controls,javafx.fxml,javafx.base,javafx.graphics --output target/JRE
      - name: jpackage
        run: jpackage --type msi --input target/ --main-jar holocron-0.1-SNAPSHOT.jar --main-class MainApplication --runtime-image target/JRE/ --name holocron
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: holocron-*.msi
  darwin:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: download jmods
        run: curl -L -o javafx-jmods-19.zip -0 https://download2.gluonhq.com/openjfx/19/openjfx-19_osx-x64_bin-jmods.zip
      - name: unpack jmods
        run: unzip javafx-jmods-19.zip
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug -p javafx-jmods-19 --add-modules javafx.controls,javafx.fxml,javafx.base,javafx.graphics --output target/JRE
      - name: jpackage
        run: jpackage --type dmg --input target/ --main-jar holocron-0.1-SNAPSHOT.jar --main-class MainApplication --runtime-image target/JRE/ --name holocron
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: darwin-dist
          path: holocron-*.dmg